* quickPublish
- to blog : creates a basic website folder if not exist or updates it
- to mail : sent well formated mail to a contact
- to pdf : produces a formated PDF/UA archive
- to odt : produces an odt doc and set its layout
- to ...

* Technologies remarquables
** Peer-tube, Spotify
Architecture hybride entre peer-to-peer et client-serveur avec switch automatique permettant de rationnaliser la bande passante

** The Elder scroll Online
Algorithmes d'interpolation coté serveur permettant initialement d'éviter la triche en jeu. Il permet de prédire les états des clients avant leurs réponse et permet de fluidifier l'expérience utilisateur. Est très intéressant lorsqu'il y a beaucoup de clients à synchroniser.

** CS Go
Ultra fast, CPU only, graphics & networking

* Questions
"Le cerveau humain n'aime pas le vide et cherchera toujours à le remplir."
Comment utiliser ce principe dans 
- La transmission de connaissance => Risque de remplissage par des hallucinations
- La conduite du changement => peut favoriser l'émergence d'idées
- L'ingénierie => à étudier

* Citations
"La première étape est de se doter d'un plan." J.M. Jancovici - PTEF

* Démarche RH
Cataloguer les compétences, prévoir plans de carrières et plans de formations

* Vendeur temple du jeux : Fabian

* Book
Multiples histoires entrelacées avec :
- des hommes de foi (religions etc.)
- des fanatiques (sectes, cultistes)
- des chercheurs, scientifiques #antarctique
- des bulletions d'informations (météo, climat, catastrophes naturelles, politique)
- des marins et explorateurs #carnets de board

Multi entités avec des capacitées distinctes (invocation, manipulation des ombres, possetion, manipulation du sang etc.)
=> restes éparpillés du maitre des âmes (the soul master)
=> tendent à converger pour se refusionner
=> maitre des âmes cherche à réduire l'influence de l'architecte dit "Dieu" depuis un conflit entre eux deux ayant entrainé la chute du soul master
(l'un crée l'autre meu)

* Phrases perso
:PROPERTIES:
:CREATED:  [2024-12-10 Tue 16:02]
:END:

On a beau parler la même langue, on ne parle pas toujours le même langage.

* Finissons en avec la fausse complexité
:PROPERTIES:
:CREATED:  [2025-03-16 Sun 19:57]
:END:

BIM CIM CAD PIM RIM LIM CDE PLM ERP BIS BOS LCV LCP ACV AVC

Vous en voulez d'autres ? 

* Markup language
:PROPERTIES:
:CREATED:  [2025-03-20 Thu 13:22]
:END:

Ergonomie

Différence entre accessibilitée ergonomique de l'utilisation du clavier Querty, Azerty etc.
Avec la représentation symbolique et l'image mentale associé aux repères 

Eg : -strique- ; +strique+ : représentation du résultat vs accès aux touches

Dactylographie : accès aux symboles f(type de clavier)

Fréquence de modification du display du texte (-strique- vs *bold* vs /italic/ vs _underline_ vs =highlight=...)

* Intermed

Service d'effacement des données personnelles => Incogni, Deletme...

Service de gestion des abonnements, y compris désabonnement

* ZKP pour preuve d'identité

Système d'autentification, preuve de l'age, anonyma...

* Verification de document

Processus humain partiellement automatisé 

Verifications superficielles de mise en page, typographie, codification et indiçage.

Pas de vérification du contenu automatique.

* Spécification vs Prescription

Besoin => fonctionnalité
Exigence => critères de performances
Spécification => charactéristiques
Prescription => solution technique

