#+glossary_sources: ~/org/glossary.org
** Contexte et motivation
*** Sclérosité systémique des lotissements traditionnels
=> Chaines de valeurs traditionnelles devenu rigides et incapable de s'adapter ou d'évoluer à cause de
      la bureaucratisation des procédés ("tamponé, double tamponé..." Au service de la France)
      la dérive des régulations (normes, réglements...)   
      la résistance au changement des collaborateurs
      l'amnésie organisationnelle et l'obsolescence des pratiques
      la déchéance du système de confiance (limites de la preuve par la formation ou par la réputation)
=> Recherche en refonte des organisation ?
=> Identification des leviers

*** Emergence de nouveaux acteurs 
(informatique et numérique, Les ESN dans la construction ?)
=> Nouveaux outils et moyens de production
=> Besoins, impacts et opportunités

La réalisation et la maintenance des maquettes numériques, en se contentant de se superposer aux métiers historiques de la construction, court le risque d’évoluer en une forme d’organisation autonome dont l’objectif principal est la pérennisation et le développement de son organisation [cite:@lourauAnalyseInstitutionnelleQuestion1973]. Cette tendance se manifeste d’ores et déjà par la refonte des organisations de projets qui incluent des structures dédiées au BIM et composées d’une ligne de management et d’un cadre contractuel adaptés aux seules finalités de cette discipline.
Cette transformation impacte inévitablement des cultures et attitudes historiquement adoptées par les acteurs des entreprises de la construction dont les délais serrés et les objectifs parfois antagonistes favorisent le maintien d’un statu quo au sein des organisations et des pratiques [cite:@lindbladBIMImplementationOrganisational2015;@paulagordogregorioContinuiteInformationnelleDans2023]. 

*** Discorde entre ergonomie et fonctionnalités
Objectif : définir le besoin de simplification, de convergence et d'apport de soin dans l'expérience utilisateur
Ergonomie des interfaces, ergonomie des flux et procédures, charge cognitive & co
=> Inéficience des ergonomies applicatives et des expériences utilisateurs, dégradées au profit d'une inflation de fonctionnalités
=> Besoin de retrouver de l'abstraction

Après avoir simplifié sa structure, simplifier ses outils et monter en compétences

Ici sourcer : Blender > All car "all-in-one" un peu moins bien c'est mieux que des verticales très maitrisés mais une absence d'interopérabilité => perte de valeur dû à la non continuité des informations, la perte de contexte, etc.
Idem possible : Notion vs MS365, Revit vs AutoCAD et ses "flavours"
etc.

Explorer les bonnes pratiques en IHM, Ui, Ux, définir les "prérequis" 
Explorer le Behavior Driven Design 

*** Conclusion
Expliquer le besoin de rééquilibrer les responsabilités et d'assainir la base avant de construire, notion de refondation de la chaine de valeur.

Objectif : proposer un cadre de travail scalable à forte valeur ajoutée et identification des rôles et périmètres 
Prérequis avant toute tentative de digitalisation (en 1 : on se remet en question et on balaie devant sa porte)
+ spécialisations horizontales versus verticale 
+ parcours de carrières (Expertise, Management, Projet)

Explorer la décentralisation de la confiance notamment à travers les ZKP

** Problématique de recherche
Question principale :

Questions complémentaires :
- Comment créer un environnement de gestion des contraintes hétéroclytes ?
- Comment décrire une contrainte en langage naturel ?


** Objectifs et contributions

** Organisation du document
