** Définition de contrainte
À l’origine, contraindre et contrainte évoquent l’idée d’une pression exercée pour restreindre la liberté d’action d’une personne [cite:@CONTRAINTEEtymologieCONTRAINTE]. Dans le langage courant, une contrainte désigne tout ce qui force ou limite la liberté d’action [cite:@DefinitionContrainte]. Par extension, le mot s’applique à toute obligation ou règle à laquelle on doit se plier et qui réduit le champ de liberté.

En outre, certains domaines techniques ont des acceptions spécifiques du terme. En droit, une contrainte peut désigner un acte coercitif [cite:@DefinitionContrainte]. En mécanique, le mot contrainte sert à traduire l’anglais stress, soit une force appliquée à un matériau qui tend à le déformer [cite:@francaiseContrainteDictionnaireLAcademie]. Ces usages spécialisés gardent néanmoins l’idée commune de force appliquée ou de limite imposée.

Dans de nombreuses normes techniques et scientifiques, le terme contrainte est employé avec un sens plus formalisé, mais toujours avec l’idée centrale de restriction imposée : 
- restriction de paramètres ou de degré de liberté (orientation, taille, position, proximité) [cite:@ISO_4351],
- restriction attachée à un type de données [cite:@ISO/CEI_2382],
- condition formelle "exprimée en langage naturel ou dans un langage formel" qui précise ou limite la sémantique d’un modèle  [cite:@ISO_19103:2024].
- borne de l’espace de recherche de solutions [cite:@ISO/CEI_2382-28] dans les systèmes experts.

En synthèse, qu’il s’agisse de géométrie, de données, de modélisation ou d’autres domaines, toutes ces définitions normatives s’accordent pour voir la contrainte comme un élément limitatif : c’est une condition, une règle ou un ensemble de paramètres qui restreignent les possibilités afin de satisfaire à des critères donnés. Une contrainte borne un espace (espace de tolérance, domaine de valeurs, comportement autorisé, etc.) *en écartant ce qui n’est pas admissible*.

Dans le domaine de l’ingénierie et de la gestion de projets de construction, on peut considérer la contrainte comme une notion englobant tous les éléments qui délimitent l’espace de solution d’un projet. Autrement dit, l’ensemble des facteurs qui, pris en compte conjointement, circonscrivent ce qu’il est possible ou acceptable de réaliser. Ces facteurs incluent :
- le contexte et les données d’entrée du projet :
    - les contraintes de site (encombrement, climat, sol),
    - les contraintes réglementaires et normatives (codes de construction, normes de sécurité),
    - les ressources disponibles (budget, délai imparti, main-d’œuvre)
- Les besoins à satisfaire
    - besoins explicitement formulés par le client ou les utilisateurs,
    - besoins implicites (non dits mais attendus)
- Les objectifs : niveau de performance ou un résultat à atteindre (par ex. efficacité énergétique visée, capacité fonctionnelle, niveau de qualité)
- Les exigences : condition à remplir ("le système doit faire X")
- Les spécifications : détaille les paramètres mesurables ("telle performance, telle dimension, tel standard à respecter")
- Les prescriptions techniques : impose les moyens à mettre en oeuvre (un équipement, un composant, un matériau).

En somme, toute condition à satisfaire, qu’elle provienne du contexte, d’un besoin, d’une règle ou d’un choix stratégique, constitue une contrainte du projet. Cette vision rejoint la définition mathématique d’une contrainte comme condition que doit satisfaire la solution d’un problème, la solution admissible étant celle qui respecte l’ensemble des contraintes. Dans un projet, les contraintes dessinent ainsi les frontières de l’acceptable : elles forment un cadre à l’intérieur duquel l’équipe de conception doit trouver sa liberté de manœuvre. Ainsi nous pouvons définir les contraintes tel que:
#+BEGIN_VERSE
Expression d'une condition, limitation ou obligation, formulée en langage naturel, qui restreint l’espace des solutions possibles afin de garantir que la solution retenue soit conforme au contexte (légal, social, sociétal, environnemental, économique et technique) du projet.

*Synonymes :* besoin, objectif, spécification, exigence.
#+END_VERSE

Par cette définition, la notion de contrainte reste agnostique du cycle de vie du projet. Qu’il s’agisse de la phase de planification, de conception, de réalisation ou d’exploitation, les contraintes forment le fil directeur immuable auquel se référer pour prendre les bonnes décisions.

** Taxonomie des contraintes
#+LATEX: \todo[inline]{Illustrer chaque catégorie de contrainte par des exemples précis}
#+LATEX: \todo[inline]{expliciter le périmètre de contrainte de la thèse}

#+BEGIN_SRC plantuml :file ./svg/taxonomie-mindmap.png
@startmindmap
 * Nature
  
 ** Technique
 *** Géométriques
 **** Espacements
 **** Tolérances
 *** Physique
 **** Énergie
 **** Signal
 **** Interférence
 **** Echauffement
 **** Vibration

 *** Chimique
 **** Couple galvanique

 ** Fonctionnelle
 *** Finacière
 **** Limite budgétaire
  
 ** Environnementale
  
 ** Sécuritaire
 *** Cybersécurité
 *** Sécurité des personnes
 *** Stockage des produits dangereux

 ** Logique

 ** Organisationnelle  
 *** Protocolaire
 **** Procédure de validation
 **** Procédure de gestion de projet
 *** Sociétale
 **** Habilitation
 **** Hiérarchie  
 **** Formation
 *** Légale
 **** Propriété intellectuelle
 *** Temporelle
 **** Disponibilité des composants
 **** Disponibilité des ressources  
 **** Dépendance des actions
 *** Contractuelle
@endmindmap 
#+END_SRC


Justifier le besoin d'une "méthode de rédaction générique".

** Médiums et volumétrie
#+LATEX: \todo[inline]{expliciter la problèmatique : taille du corpus, diversité des sources, silotage des rédactions (pas de travail conjoint entre les organismes producteurs de contraintes), difficulté d'en connaitre, etc.}
Sources, origines et finalités

# Définition
Brevets, Normes, Législation, Contrats, Jurisprudences...

Volume conséquent => faire un compte du nombre de pages par domaine pour illustrer la problématique.

#+CAPTION: Proposition de représentation des environnements de contraintes
#+NAME: fig:360-view-engineering-environment
#+ATTR_LATEX: :placement [htbp]
[[./svg/360-view-engineering-environment.pdf]]

#+LATEX: \todo[inline]{voie de recherche possible : création d'un service de fourniture de contrainte standardisé et unifié appelable via des requettes API}

** Exercice des contraintes
#+LATEX: \todo[inline]{expliciter le cycle de vie des contraintes}
Dans l'industrie de la construction, les parties prenantes se coordonnent dans la réponse à des exigences exprimées. Cette gestion des éxigences vise l'atteinte des objectifs du client en respect des contraintes légales, réglementaires et normatives.

#+BEGIN_QUOTE
Les exigences sont déterminées à partir des besoins des parties prenantes et des contraintes comme les conditions d’utilisation, les ressources et la législation. -- NF EN 60300-1:2014[cite:@GestionSureteFonctionnement2014]
#+END_QUOTE

La relation entre éxigences et contraintes est représentée par la [[fig:relation-contraintes-exigences]]. Ainsi, une exigence est une spécification d'un besoin tenant compte des contraintes du domaine d'étude. Cependant, la limite est souvent floue entre un besoin, une contrainte et une exigence. Les professionnels de la construction ont donc tendance à les mélanger.

#+CAPTION: La relation entre contraintes et exigences selont l'ISO 60300-1[cite:@GestionSureteFonctionnement2014]
#+NAME: fig:relation-contraintes-exigences
#+ATTR_LATEX: :placement [htbp]
[[./svg/relation-contraintes-exigences.pdf]]

Une matrice de traçabilité des exigences est employé pour réalisé le suivi des exigences.

Elle se matérialise par un tableau ou un document qui relie les exigences d'un projet aux livrables, tâches, jalons ou tests qui les satisfont. Son objectif principal est de garantir que toutes les exigences sont couvertes par les plans du projet et qu'aucun besoin n'est négligé. Elle permet également de vérifier l'impact des modifications d'exigences, facilitant la gestion des changements.

Élaboration de la matrice :
1. Collecte des exigences : rassembler toutes les exigences du projet, qu'elles proviennent du cahier des charges, des réunions avec les parties prenantes, d'autres documents de projet ainsi que des textes institutionnels applicables.
2. Identification des livrables : Listez tous les livrables du projet, y compris les rapports, les documents, le code source, les schémas, les maquettes numériques, les plans, etc.
3. Préparer la matrice : la première colonne source les exigences et la première ligne source les livrables. La première cellule (eg. A1:A1) est laissée vide. 
4. Affecter les livrables aux exigences : Une croix est inscrite à l'intersection de chaque exigence devant être respectée ou vérifiée par un livrable. Un livrable peut être affecté à plusieurs exigences et une exigence peut nécessiter plusieurs livrables pour être vérifié. Cette étape nécessite une compréhension approfondie du projet et une collaboration étroite avec les équipes techniques.

Utilisation de la matrice :
- Vérification de la couverture des exigences : la matrice permet de s'assurer que chaque exigence est adressée par au moins un livrable, réduisant ainsi le risque d'omissions.
- Gestion des changements : Lorsque des modifications sont apportées à une exigence, la matrice facilite l'identification des livrables impactés, aidant à évaluer l'ampleur et l'impact du changement sur le projet.
- Communication avec les parties prenantes : La matrice fournit une vue d'ensemble claire qui peut être utilisée pour communiquer l'avancement du projet et la manière dont les exigences sont satisfaites, renforçant la confiance des parties prenantes.
- Facilitation des tests : En liant les exigences aux cas de test, la matrice aide à s'assurer que tous les aspects du système sont correctement testés, contribuant à la qualité du produit final.

La matrice de traçabilité des exigences est un document vivant qui *doit être régulièrement mis à jour tout au long du projet*. Les ajouts, les suppressions ou les modifications d'exigences, ainsi que l'évolution des plans de livrables, doivent être reflétés dans la matrice pour maintenir sa précision et sa pertinence.
Elle est employée en complément d'une liste des documents exécutés par le prestataire.

La nature de sa composition s'apparente à une table de jonction d'une base de donnée relationnelle tel que pourrait définir, sous forme de MLD la figure [[fig:db-exigences-lde]].

#+CAPTION: MLD - Association des éxigences aux livrables
#+NAME: fig:db-exigences-lde
#+ATTR_LATEX: :placement [htbp]
[[./svg/db-exigences-lde.pdf]]

** Cadre de travail
#+LATEX: \todo[inline]{on pose ici les 3 composantes du projet de recherche lié aux contraintes}
Les contraintes étant centraux à la caractérisation d'un ouvrage, il convient de définir un cadre de travail rigoureux permettant leurs manipulation.

Ce cadre doit poséder à minimum 3 composantes :
- Modélisation : formulation, négociation et amélioration des contraintes ;
- Résolution : vérification de l'espace de solution, contrôle automatisé du respect des contraintes ;
- Préservation : suivi des évolutions, association contextuelle, recherche d'information, etc.

Modélisation des contraintes : c’est l’activité de formulation et de négociation des contraintes en amont et au fil du projet. Il s’agit d’identifier clairement toutes les contraintes pertinentes (contextuelles, contractuelles, techniques…), de les exprimer de façon non ambiguë (rédaction dans le cahier des charges, spécifications, notes de calcul, modèles UML, etc.) et de s’assurer qu’elles sont comprises et acceptées par les parties prenantes. La modélisation inclut éventuellement la négociation de certaines contraintes : par exemple discuter d’une tolérance plus large si une exigence s’avère trop restrictive par rapport au coût, ou reformuler un besoin implicite en exigences explicites testables. Un bon modèle de contraintes se veut complet, traçable et partagé par tous, servant de référence commune.

Résolution des contraintes : ce volet recouvre la satisfaction effective des contraintes lors de la recherche de solution et de la réalisation du projet. Il s’agit d’abord de procéder à la résolution du problème en trouvant un espace de solution qui respecte l’ensemble des contraintes identifiées – en d’autres termes, vérifier qu’il existe au moins une solution faisable (vérification de la non-surcontrainte). Ensuite, on s’assure du juste niveau de contrainte : éviter d’ajouter des contraintes inutiles ou trop sévères qui surcontraindraient le projet par rapport au besoin réel. Cela implique une optimisation : assez de contraintes pour rencontrer le besoin et les objectifs, mais pas au point d’éliminer des solutions viables ou d’alourdir le projet inutilement. Enfin, ce volet inclut la vérification du respect des contraintes tout au long des études et de l’exécution – par des revues de conception, des simulations, des prototypes ou des tests. Chaque décision technique ou modification doit être évaluée au prisme des contraintes : si une solution envisagée viole une contrainte (par exemple une charge dépassant la contrainte de poids maximal), il faut soit l’ajuster, soit envisager de redéfinir la contrainte si cela est justifié et approuvé.

Préservation des contraintes (capitalisation) : au-delà du respect ponctuel, il est crucial de préserver la mémoire des contraintes du projet et de leur évolution. Ce troisième volet consiste à historiser et documenter les contraintes, leurs justifications d’origine, et les éventuelles modifications apportées en cours de route (assouplissements, ajouts, suppressions), de sorte que l’on sache à tout moment pourquoi telle contrainte a été posée et pourquoi tel choix de conception a été fait en conséquence. Cette traçabilité garantit la cohérence du projet sur la durée et facilite la maintenance ou les évolutions futures. Par exemple, conserver dans un registre ou une base de connaissance le raisonnement ayant conduit à une contrainte particulière (issue d’une norme, d’un retour d’expérience, d’une demande client spécifique…) permettra, des années plus tard, à un nouvel intervenant de comprendre le rationnel de conception. La préservation des contraintes et de leur historique de négociation contribue ainsi à une gestion de configuration rigoureuse et à l’amélioration continue du référentiel de conception de l’entreprise.

En conjuguant ces trois dimensions, on dote la notion de contrainte d’un véritable cadre de gestion sur le projet. Cela permet d’assurer la définition unifiée de "contrainte" proposée au paragraphe [[Définition de contrainte]].

** Méthodes de traitement
Langage naturel :
- Rédaction
- Affectation (par des tableaux et matrices)
- Relecture (sur la base de listes à puces, checklist)
- Simulations (éventuellement mais loop sur rapport produit)
- Model checking : vérification exhaustive d'états finis, non systématique à date et loop sur rapport produit

** Conclusion
