#+glossary_sources: ~/org/glossary.org
** Introduction
# Précise le statut scientifique du travail (projet de recherche, ancrage institutionnel, etc.)

# Présenter le contexte normatif croissant dans la construction.

# Problématique : la difficulté d’accès et de quantification de la charge normative, les impacts potentiels de l'ampleur et la difficulté d'en connaitre

# Objectif : quantifier, caractériser et comparer la norme dans la construction.

** Périmètre de l'étude
L’étude se concentre sur les normes volontaires françaises (NF) référencées par AFNOR et publiées à la date de la collecte.
Le périmètre inclut toutes les normes relevant du domaine “Construction et urbanisme” selon la classification AFNOR Norm’Info.

Les normes ISO/IEC sont souvent transposées en normes NF (NF EN ISO, etc.)

AFNOR est le point d’entrée national reconnu par l’État pour la normalisation volontaire.

Les normes d’application obligatoire sont issues de ce corpus (via réglementations).

Par l'analyse des textes et de leurs métadonnées, nous tenterons de répondre aux questions suivantes :

- Q1 : Quelle est l’ampleur documentaire du corpus normatif applicable à l’industrie de la construction, mesurée en nombre de documents et en volume paginé ?
- Q2 : La filière construction présente-t-elle une densité normative supérieure à celle d’autres secteurs industriels comparables, en termes de nombre de normes actives et de leur volumétrie documentaire ?
- Q3 : Comment les textes normatifs se répartissent-ils entre les sous-domaines techniques, professions et spécialités représentatives de la filière construction, selon les descripteurs et indices de classement ?


** Méthodologie
*** Cadre juridique
Il n'existe pas de base de données publiques recenssant l'ensemble des textes de normes et leurs métadonnées. Il convient donc de constituer cette base de donnée en collectant les informations publiquement accessibles.

Cette opération implique l'emplois du webscraping.

#+BEGIN_QUOTE
Le webscraping consiste à extraire automatiquement (to scrape : gratter), de manière massive des données d'un site web. -- INRAE[cite:@quesnevilleRecommandationsUsagesWebscraping2024]
#+END_QUOTE

La légalité d'une telle opération semble parfois faire débat. (ref à ajouter)

Certains acteurs, notamment l'AFNOR, s'oppose à la fouille automatisée des texte que l'organisme fournis ainsi qu'à l'emploi de modèles d'intelligence artificielle sur ceux-ci tels que l'exprime ce paragraphe apposés en première page de couverture :
#+BEGIN_QUOTE
AFNOR, en tant que titulaire des droits d’auteur ou distributeur autorisé, s’oppose expressément à toute intégration, transmission ou absorption totale ou partielle du présent document par des moteurs ou algorithmes d’Intelligence Artificielle (IA). AFNOR s’oppose également à toute fouille de textes et de données ou création dérivée produite par une IA et basée sur le présent document.
#+END_QUOTE

Cela dit, le Code de la propriété intellectuelle précise les modalités de copie et de reproduction des bases de données (Art. L342-3) et les droits de manipulation des textes dans un cadre de recherche scientifique (Art. L122-5 et L122-5-3)[cite:@CodeProprieteIntellectuelle] en précisant spécifiquement que :
#+BEGIN_QUOTE
Des copies ou reproductions numériques d'œuvres auxquelles il a été accédé de manière *licite* peuvent être réalisées *sans autorisation des auteurs* en vue de *fouilles de textes et de données* menées à bien aux seules fins de la recherche scientifique par les organismes de recherche [...] ou pour leur compte et à leur demande par d'autres personnes, y compris dans le cadre d'un partenariat sans but lucratif avec des acteurs privés. -- Article L122-5-3[cite:@CodeProprieteIntellectuelle]
#+END_QUOTE

L'exploration des textes publiés par l'AFNOR et obtenus de manière licite est donc autorisée.

*** Données collectées
Métadonnées accessibles publiquement via Norm’Info et Boutique AFNOR :
    Référence (ex : NF C15-100)
    Titre
    Date de publication
    Nombre de pages
    Codes ICS
    Indice de classement
    Domaine technique
    Commission de normalisation
# Prévois un tableau synthétique des métadonnées collectées pour la transparence méthodologique

*** Protocole technique
Méthode de collecte : Web scraping (à documenter)

# Langage : Python 3
# Stockage : Fichier CSV encodé UTF-8

Limite : seules les normes publiées et publiquement référencées sur le site marchand de l'AFNOR disponibles à la vente ou référencées, sont incluses.

#+CAPTION: Code de collecte des informations
#+NAME: fig:afnor.py
#+ATTR_LATEX: :placement [htbp]
#+BEGIN_SRC python :results verbatim

#+END_SRC

** Méthodes d'analyse
    Analyse descriptive :
        Nombre total de documents / pages
        Évolution temporelle des publications (si date disponible)

    Analyse comparative :
        Densité normative dans la construction vs autres domaines AFNOR (en comparant les volumes ICS sectoriels)

    Analyse thématique / taxonomique :
        Catégorisation des normes par code ICS, indice de classement, domaine technique
        Projection possible par métier : architecture, génie civil, thermique, électricité…

Outils recommandés : Python (pandas + matplotlib)

** Résultats obtenus
Cartographie de la norme dans la construction
# Vis : Graphe, Timeline

Poids normatif par spécialité
# Vis : diagramme de barre,

Identification d’une sur-normativité éventuelle

Premiers indicateurs pour évaluer la « charge de la norme »
# Vis : Quantification des pages par documents et par périmètres : diagramme de boite à moustache ou violon

** Discussion et perspectives


